Image_Base = "ubuntu/trusty64"

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, '--cpus', '1']
    vb.customize ["modifyvm", :id, '--memory', '1024']
    vb.customize ["modifyvm", :id, '--cpuexecutioncap', '100']
  end

  config.vm.define "Web1" do |node|
    node.vm.box = Image_Base
    node.vm.hostname = "Web1"
    node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    node.vm.synced_folder "www_1/", "/var/www/html"
    node.vm.provision "shell", path: "Vagrant/script.sh"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, '--name', 'Web1' ]
    end
  end

  config.vm.define "Web2" do |node|
    node.vm.box = Image_Base
    node.vm.hostname = "Web2"
    node.vm.network "forwarded_port", guest: 80, host: 8008, host_ip: "127.0.0.1"
    node.vm.synced_folder "www_2/", "/var/www/html"
    node.vm.provision "shell", path: "Vagrant/script.sh"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, '--name', 'Web2' ]
    end
  end

end
