Image_Base = "ubuntu/trusty64"

Vagrant.configure("2") do |config|
  
  config.vm.define "ServerWeb" do |node|
    node.vm.box = Image_Base
    node.vm.hostname = "ServerWeb"
    node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
