Image_Base = "ubuntu/trusty64"

Vagrant.configure("2") do |config|
  
  config.vm.define "ServerWeb" do |node|
    node.vm.box = Image_Base
    node.vm.hostname = "ServerWeb"
    #node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, '--name', 'demo-00' ]
      vb.customize ["modifyvm", :id, '--cpus', '1']
      vb.customize ["modifyvm", :id, '--memory', '720']
      vb.customize ["modifyvm", :id, '--cpuexecutioncap', '80']
      vb.customize ["modifyvm", :id, '--natpf1', 'HTTP,tcp,127.0.0.1,8080,,80'] 
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end