Image_Base = "ubuntu/trusty64"

Vagrant.configure("2") do |config|
 config.vm.define "ServerWeb" do |node|
    node.vm.box = Image_Base
    node.vm.hostname = "ServerWeb"
    node.vm.provision "shell", path: "Vagrant/script.sh"
    node.vm.synced_folder "www/", "/var/www/html"
    node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", id: "HTTP"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, '--name', 'ServerWeb (Vagrant)' ]
      vb.customize ["modifyvm", :id, '--cpus', '1']
      vb.customize ["modifyvm", :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, '--cpuexecutioncap', '100']
    end
  end
end
